print("Basic Arithmetic Operators")
print("2 + 2:", 2+2)
print("4 - 2:", 4-2)
print("6 * 5:", 6*5)
print("5 / 2:", 5/2)
print("2 ** 2:", 2**2)
print("5 % 2:", 5%2)
print("\nParentheses can override order of operations!")
print("2 + 2 * 5:", 2+2*5)
print("(2 + 2) * 5:", (2+2)*5)

print("\nString Operators")
print("'word' + 'stem': ", "word"+"stem")
print("'repeat' * 3:", "repeat"*3)
print("'na' * 8 + ' Batman!':", "na"*8+" Batman!")